#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

homepage:
    path: /
    defaults: { _controller: AppBundle:Default:index }

new_form:
    path: /form
    defaults: { _controller: AppBundle:Default:new }

blog_list:
    path: /blog/{page}
    defaults: { _controller: AppBundle:Blog:list, page: 1 }
    requirements:
        page: \d+

blog_show:
    path: /blog/{slug}
    defaults: { _controller: AppBundle:Blog:show }

lucky_number:
    path: /lucky/number/{max}
    defaults: { _controller: AppBundle:Lucky:randomize, max: 100 }

return_json:
    path: /json
    defaults: { _controller: AppBundle:Blog:returnJson }